{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_test.py:25: Exception"}, "start": 1691486146518, "stop": 1691486146518, "uuid": "4d555c95-eed2-471e-b6a3-39ab86db47e6", "historyId": "e1b46ab4774530d569c8bf359163de7f", "testCaseId": "e1b46ab4774530d569c8bf359163de7f", "fullName": "test_test#test_broken", "labels": [{"name": "suite", "value": "test_test"}, {"name": "host", "value": "DELL-0O8SAEAM4H"}, {"name": "thread", "value": "3248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_test"}]}